//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class InputKeyboardBitsMsg : Message
    {
        public const string k_RosMessageName = "unity_msgs/InputKeyboardBits";
        public override string RosMessageName => k_RosMessageName;

        public ushort bits;

        public InputKeyboardBitsMsg()
        {
            this.bits = 0;
        }

        public InputKeyboardBitsMsg(ushort bits)
        {
            this.bits = bits;
        }

        public static InputKeyboardBitsMsg Deserialize(MessageDeserializer deserializer) => new InputKeyboardBitsMsg(deserializer);

        private InputKeyboardBitsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.bits);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.bits);
        }

        public override string ToString()
        {
            return "InputKeyboardBitsMsg: " +
            "\nbits: " + bits.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
